=== Femaf/verefoo/xsd/nfvInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2017 Politecnico di Torino and others.
 All rights reserved. This program and the accompanying materials
 are made available under the terms of the Apache License, Version 2.0
 which accompanies this distribution, and is available at
 http://www.apache.org/licenses/LICENSE-2.0
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:include schemaLocation="errorSchema.xsd"/>
    <xsd:include schemaLocation="hateoasLinks.xsd"/>
    <xsd:include schemaLocation="xml_components.xsd"/>
	<xsd:element name="NFV">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="graphs" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="CapacityDefinition" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="PropertyDefinition" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="Hosts"/>
				<xsd:element ref="Connections"/>
				<xsd:element name="ParsingString" type="xsd:string" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>		
	    <xsd:key name="hostKey">
	      <xsd:selector xpath="Hosts/Host" />
	      <xsd:field xpath="@name" />
	    </xsd:key>
	    <xsd:keyref name="ConnectionSourceHost" refer="hostKey">
	      <xsd:selector xpath="Connections/Connection" />
	      <xsd:field xpath="@sourceHost" />
	    </xsd:keyref>
	    <xsd:keyref name="ConnectionDestHost" refer="hostKey">
	      <xsd:selector xpath="Connections/Connection" />
	      <xsd:field xpath="@destHost" />
	    </xsd:keyref>
	    
	    <xsd:keyref name="CapacityRef" refer="keyNode">
	      <xsd:selector xpath="CapacityDefinition/CapacityForNode" />
	      <xsd:field xpath="@node" />
	    </xsd:keyref>
	    
	    <xsd:key name="keyGraph">
            <xsd:selector xpath="graphs/graph" />
            <xsd:field xpath="@id" />
        </xsd:key>
	    <xsd:keyref name="PropertyRef" refer="keyGraph">
	      <xsd:selector xpath="PropertyDefinition/Property" />
	      <xsd:field xpath="@graph" />
	    </xsd:keyref>
	</xsd:element>
	<xsd:element name="PropertyDefinition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Property" type="Property" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="CapacityDefinition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="CapacityForNode" type="NodeCapacity" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="NodeCapacity">
		<xsd:attribute name="node" type="xsd:string"/>	
		<xsd:attribute name="capacity" type="xsd:int"/>
	</xsd:complexType>
	<xsd:element name="Hosts">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="Host"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Host">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="NodeRef" type="NodeRefType" maxOccurs="unbounded" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="diskStorage" type="xsd:int" use="required"/>
			<xsd:attribute name="type" type="TypeOfHost" use="optional"/>
			<xsd:attribute name="active" type="xsd:boolean" use="optional" default="false"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Connections">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="Connection"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Connection">
		<xsd:complexType>
			<xsd:attribute name="sourceHost" type="xsd:string" use="required"/>
			<xsd:attribute name="destHost" type="xsd:string" use="required"/>
			<xsd:attribute name="avgLatency" type="xsd:int"/>
		</xsd:complexType>
		</xsd:element>
	<xsd:complexType name="NodeRefType">
		<xsd:attribute name="node" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:simpleType name="TypeOfHost">
	    <xsd:restriction base="xsd:string">
	      <xsd:enumeration value="CLIENT"/>
	      <xsd:enumeration value="SERVER"/>
	      <xsd:enumeration value="MIDDLEBOX"/>
	 	</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="P-Name">
	    <xsd:restriction base="xsd:string">
	      <xsd:enumeration value="IsolationProperty"/>
	 	</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Property">
				<xsd:attribute name="name" type="P-Name" use="required"/>
				<xsd:attribute name="isSat" type="xsd:boolean"/>
				<xsd:attribute name="graph" type="xsd:long" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== Femaf/verefoo/testfile/UNIV1.xml
<?xml version="1.0" encoding="UTF-8"?>
<NFV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/nfvInfo.xsd">
  <graphs>
    <graph id="0">
     <node functional_type="WEBCLIENT" name="nodeA">
        <neighbour name="node1"/>
        <configuration description="A simple description" name="confA">
          <webclient nameWebServer="nodeB"/>
        </configuration>
      </node>
      <node functional_type="FIREWALL" name="node1">
        <neighbour name="nodeA"/>
        <neighbour name="node2"/>
        <configuration description="A simple description" name="conf1">
          <firewall>
            <elements>
              <source>nodeC</source>
              <destination>nodeD</destination>
            </elements>
          </firewall>
        </configuration>
      </node>
      <node functional_type="DPI" name="node2">
        <neighbour name="node1"/>
        <neighbour name="node3"/>
        <configuration description="A simple description" name="conf2">
          <dpi>
          	<notAllowed>nodeC</notAllowed>
          </dpi>
        </configuration>
      </node>
      <node functional_type="CACHE" name="node3">
        <neighbour name="node2"/>
        <neighbour name="node4"/>
        <configuration description="A simple description" name="conf3">
          <cache>
          	<resource>nodeA</resource>
          	<resource>node1</resource>
          	<resource>node2</resource>
          </cache>
        </configuration>
      </node>
	  <node functional_type="NAT" name="node4">
        <neighbour name="node3"/>
        <neighbour name="nodeB"/>
        <configuration description="A simple description" name="conf4">
         <nat>
          		<source>nodeA</source>
          		<source>node1</source>
          		<source>node2</source>
          		<source>node3</source>
          </nat>
        </configuration>
      </node>
   
      <node functional_type="WEBSERVER" name="nodeB">
        <neighbour name="node4"/>
        <configuration description="A simple description" name="confB">
          <webserver>
          	<name>nodeB</name>
          </webserver>
        </configuration>
      </node>
    </graph>
  </graphs>
  <CapacityDefinition>
   		<CapacityForNode node="node1" capacity="50"/>
  		<CapacityForNode node="node2" capacity="50"/>
  		<CapacityForNode node="node3" capacity="68"/>
  		<CapacityForNode node="node4" capacity="45"/>
  </CapacityDefinition>
  <PropertyDefinition>
  		<Property graph="0" name="IsolationProperty"/> 		
  </PropertyDefinition>
   <Hosts>
        <Host name="N1" diskStorage="108" type="CLIENT"/>
        <Host name="N2" diskStorage="122" type="MIDDLEBOX"/>
        <Host name="N3" diskStorage="116" type="MIDDLEBOX"/>
        <Host name="N4" diskStorage="125" type="MIDDLEBOX"/>
        <Host name="N5" diskStorage="100" type="MIDDLEBOX"/>
        <Host name="N6" diskStorage="124" type="MIDDLEBOX"/>
        <Host name="N7" diskStorage="141" type="MIDDLEBOX"/>
        <Host name="N8" diskStorage="116" type="MIDDLEBOX"/>
        <Host name="N9" diskStorage="127" type="MIDDLEBOX"/>
        <Host name="N10" diskStorage="120" type="MIDDLEBOX"/>
        <Host name="N11" diskStorage="130" type="MIDDLEBOX"/>
        <Host name="N12" diskStorage="116" type="MIDDLEBOX"/>
        <Host name="N13" diskStorage="121" type="MIDDLEBOX"/>
        <Host name="N14" diskStorage="122" type="MIDDLEBOX"/>
        <Host name="N15" diskStorage="124" type="MIDDLEBOX"/>
        <Host name="N16" diskStorage="134" type="MIDDLEBOX"/>
        <Host name="N17" diskStorage="105" type="MIDDLEBOX"/>
        <Host name="N18" diskStorage="118" type="MIDDLEBOX"/>
        <Host name="N19" diskStorage="123" type="MIDDLEBOX"/>
        <Host name="N20" diskStorage="138" type="MIDDLEBOX"/>
        <Host name="N21" diskStorage="144" type="MIDDLEBOX"/>
        <Host name="N22" diskStorage="134" type="MIDDLEBOX"/>
        <Host name="N23" diskStorage="136" type="MIDDLEBOX"/>
        <Host name="N24" diskStorage="113" type="SERVER"/>
    </Hosts>
    <Connections>
        <Connection sourceHost="N20" destHost="N3" avgLatency="162160"/>
        <Connection sourceHost="N3" destHost="N20" avgLatency="162160"/>
        <Connection sourceHost="N20" destHost="N4" avgLatency="280094"/>
        <Connection sourceHost="N4" destHost="N20" avgLatency="280094"/>
        <Connection sourceHost="N20" destHost="N12" avgLatency="398029"/>
        <Connection sourceHost="N12" destHost="N20" avgLatency="398029"/>
        <Connection sourceHost="N20" destHost="N15" avgLatency="987701"/>
        <Connection sourceHost="N15" destHost="N20" avgLatency="987701"/>
        <Connection sourceHost="N17" destHost="N20" avgLatency="88450"/>
        <Connection sourceHost="N20" destHost="N17" avgLatency="88450"/>
        <Connection sourceHost="N20" destHost="N22" avgLatency="1105636"/>
        <Connection sourceHost="N22" destHost="N20" avgLatency="1105636"/>
        <Connection sourceHost="N20" destHost="N23" avgLatency="619156"/>
        <Connection sourceHost="N23" destHost="N20" avgLatency="619156"/>
        <Connection sourceHost="N21" destHost="N10" avgLatency="309578"/>
        <Connection sourceHost="N10" destHost="N21" avgLatency="309578"/>
        <Connection sourceHost="N23" destHost="N9" avgLatency="456996"/>
        <Connection sourceHost="N9" destHost="N23" avgLatency="456996"/>
        <Connection sourceHost="N23" destHost="N14" avgLatency="280094"/>
        <Connection sourceHost="N14" destHost="N23" avgLatency="280094"/>
        <Connection sourceHost="N23" destHost="N24" avgLatency="117934"/>
        <Connection sourceHost="N24" destHost="N23" avgLatency="117934"/>
        <Connection sourceHost="N24" destHost="N14" avgLatency="176901"/>
        <Connection sourceHost="N14" destHost="N24" avgLatency="176901"/>
        <Connection sourceHost="N2" destHost="N12" avgLatency="796058"/>
        <Connection sourceHost="N12" destHost="N2" avgLatency="796058"/>
        <Connection sourceHost="N2" destHost="N15" avgLatency="884509"/>
        <Connection sourceHost="N15" destHost="N2" avgLatency="884509"/>
        <Connection sourceHost="N3" destHost="N14" avgLatency="545447"/>
        <Connection sourceHost="N14" destHost="N3" avgLatency="545447"/>
        <Connection sourceHost="N3" destHost="N15" avgLatency="840283"/>
        <Connection sourceHost="N15" destHost="N3" avgLatency="840283"/>
        <Connection sourceHost="N4" destHost="N8" avgLatency="648640"/>
        <Connection sourceHost="N8" destHost="N4" avgLatency="648640"/>
        <Connection sourceHost="N3" destHost="N5" avgLatency="398029"/>
        <Connection sourceHost="N5" destHost="N3" avgLatency="398029"/>
        <Connection sourceHost="N5" destHost="N6" avgLatency="206385"/>
        <Connection sourceHost="N6" destHost="N5" avgLatency="206385"/>
        <Connection sourceHost="N5" destHost="N15" avgLatency="456996"/>
        <Connection sourceHost="N15" destHost="N5" avgLatency="456996"/>
        <Connection sourceHost="N6" destHost="N15" avgLatency="250610"/>
        <Connection sourceHost="N15" destHost="N6" avgLatency="250610"/>
        <Connection sourceHost="N8" destHost="N22" avgLatency="191643"/>
        <Connection sourceHost="N22" destHost="N8" avgLatency="191643"/>
        <Connection sourceHost="N10" destHost="N15" avgLatency="456996"/>
        <Connection sourceHost="N15" destHost="N10" avgLatency="456996"/>
        <Connection sourceHost="N11" destHost="N15" avgLatency="368545"/>
        <Connection sourceHost="N15" destHost="N11" avgLatency="368545"/>
        <Connection sourceHost="N15" destHost="N16" avgLatency="29483"/>
        <Connection sourceHost="N16" destHost="N15" avgLatency="29483"/>
        <Connection sourceHost="N17" destHost="N1" avgLatency="353803"/>
        <Connection sourceHost="N1" destHost="N17" avgLatency="353803"/>
        <Connection sourceHost="N18" destHost="N11" avgLatency="280094"/>
        <Connection sourceHost="N11" destHost="N18" avgLatency="280094"/>
        <Connection sourceHost="N18" destHost="N21" avgLatency="280094"/>
        <Connection sourceHost="N21" destHost="N18" avgLatency="280094"/>
        <Connection sourceHost="N2" destHost="N19" avgLatency="398029"/>
        <Connection sourceHost="N19" destHost="N2" avgLatency="398029"/>
        <Connection sourceHost="N15" destHost="N19" avgLatency="486480"/>
        <Connection sourceHost="N19" destHost="N15" avgLatency="486480"/>
        <Connection sourceHost="N15" destHost="N18" avgLatency="235869"/>
        <Connection sourceHost="N18" destHost="N15" avgLatency="235869"/>
        <Connection sourceHost="N1" destHost="N9" avgLatency="943476"/>
        <Connection sourceHost="N9" destHost="N1" avgLatency="943476"/>
        <Connection sourceHost="N1" destHost="N20" avgLatency="427512"/>
        <Connection sourceHost="N20" destHost="N1" avgLatency="427512"/>
        <Connection sourceHost="N12" destHost="N22" avgLatency="751832"/>
        <Connection sourceHost="N22" destHost="N12" avgLatency="751832"/>
        <Connection sourceHost="N8" destHost="N20" avgLatency="928734"/>
        <Connection sourceHost="N20" destHost="N8" avgLatency="928734"/>
        <Connection sourceHost="N2" destHost="N5" avgLatency="781316"/>
        <Connection sourceHost="N5" destHost="N2" avgLatency="781316"/>
        <Connection sourceHost="N5" destHost="N12" avgLatency="855025"/>
        <Connection sourceHost="N12" destHost="N5" avgLatency="855025"/>
        <Connection sourceHost="N11" destHost="N16" avgLatency="339061"/>
        <Connection sourceHost="N16" destHost="N11" avgLatency="339061"/>
        <Connection sourceHost="N18" destHost="N16" avgLatency="221127"/>
        <Connection sourceHost="N16" destHost="N18" avgLatency="221127"/>
        <Connection sourceHost="N16" destHost="N10" avgLatency="427512"/>
        <Connection sourceHost="N10" destHost="N16" avgLatency="427512"/>
